services:
  redis-cache:
    build:
      dockerfile: services/redis/redis.Dockerfile
    container_name: newsapi-redis-cache
    ports:
      - "6378:6379"
    volumes:
      - ./services/data/cache:/data
    restart: unless-stopped
    networks:
      - newsapi-network
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: news_sentiment_warehouse
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./services/data/data:/var/lib/postgresql/data
      - ./services/timescale_db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./services/timescale_db/pg_hba.conf:/docker-entrypoint-initdb.d/pg_hba.conf
      - ./services/timescale_db/setup_pg_hba.sh:/docker-entrypoint-initdb.d/02-setup_pg_hba.sh
    restart: unless-stopped
networks:
  newsapi-network:
    driver: bridge