services:
  redis-cache:
    build:
      dockerfile: services/redis/redis.Dockerfile
    container_name: newsapi-redis-cache
    ports:
      - "6378:6379"
    volumes:
      - ./data/cache:/data
    restart: unless-stopped
    networks:
      - newsapi-network
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: news_sentiment_warehouse
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/data:/var/lib/postgresql/data
      - ./timescale_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
networks:
  newsapi-network:
    driver: bridge